Create portfolio layout
sebz996/front-end-web-developer-course pull request #5
Opened 2022-05-28 06:02 UTC by sebz996

Udacity project.

# Prototype:
![image](https://user-images.githubusercontent.com/106308738/170812314-b89602de-a9d7-4263-a860-93ab3a5c48ea.png)

# Result:
![image](https://user-images.githubusercontent.com/106308738/170812324-1d546752-a9de-4470-bda3-bf7c2dbd9951.png)

2022-05-28 12:19 UTC, Martian2Lee requested changes
not best practice, please update

2022-05-28 14:02 UTC, sebz996 commented
Done.

2022-05-29 00:48 UTC, sebz996 commented
Done. 

![image](https://user-images.githubusercontent.com/106308738/170847400-63a48939-9fe5-4950-b4e1-6febc128a226.png)

2022-05-29 09:03 UTC, Martian2Lee requested changes
1. need padding below "Featured Word"
2. less padding between works
3. need bigger font
4. need bigger font and vertical padding
The above issues fall under one category, please ask me to explain in the call.
<img width="799" alt="Screen Shot 2022-05-29 at 16 52 42" src="https://user-images.githubusercontent.com/22679825/170860186-fba1d344-907a-41ab-b01a-d5c575e0f09b.png">

2022-05-29 09:03 UTC, Martian2Lee commented on portfolio/css/style.css
> +header div {
bad identifier, ask me to explain in the call

2022-05-29 09:03 UTC, Martian2Lee commented on portfolio/css/style.css
> +    justify-content: space-between;
👍

2022-05-30 14:00 UTC, seb-lex commented on portfolio/css/style.css
> +    justify-content: space-between;
Changes requested:

![image](https://user-images.githubusercontent.com/106308738/171007871-dc981510-02cc-4393-bde4-5e68249075d3.png)

2022-05-30 14:24 UTC, Martian2Lee approved these changes
🚀

2022-05-30 14:24 UTC, merged